server:
  port: 9091

mysql:
  url: jdbc:mysql://localhost:3306/dbtest?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;autoReconnectForPools=true
  username: root
  password: root

spring:
  mvc:
    dispatch-options-request: true
    favicon:
      enabled: false
  aop:
    auto: true
  profiles:
    active: test

