server:
  port: 9091

mysql:
  url: jdbc:mysql://localhost:3306/dbtest1?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;autoReconnectForPools=true
  username: root
  password: root

spring:
  mvc:
    dispatch-options-request: true
    favicon:
      enabled: false
  aop:
    auto: true
  profiles:
    active: test

redis:
  r1:
    host: 127.0.0.1
    port: 6379
  r2:
    host: 127.0.0.1
    port: 6379
  r3:
    host: 127.0.0.1
    port: 6379

